spring:
  application:
    name: store

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD, EUR, CAD

payment-gateway: paypal

database-type: in-memory

notification-type: email